import { Section } from '../../schema';

export const canActivitiesSection: Section = {
  id: 'g3-english-can-activities',
  grade: 3,
  subject: 'english',
  section: 'can-activities',
  title: 'Я вмію! (can / can\'t)',
  lessons: [
    {
      id: 'g3-en-can-activities-l1',
      title: 'Речі',
      exercises: [
        {
          id: 'g3-en-can-activities-l1-e01',
          type: 'choice',
          prompt: 'Як англійською "мушлі"?',
          options: ['puzzles', 'shells', 'bears'],
          answer: 'shells',
          speak: true,
        },
        {
          id: 'g3-en-can-activities-l1-e02',
          type: 'choice',
          prompt: 'Яке слово означає "пазли"?',
          options: ['shells', 'teddy bears', 'puzzles'],
          answer: 'puzzles',
          speak: true,
        },
        {
          id: 'g3-en-can-activities-l1-e03',
          type: 'choice',
          prompt: 'Як кажуть "плюшеві ведмедики"?',
          options: ['puzzles', 'shells', 'teddy bears'],
          answer: 'teddy bears',
          speak: true,
        },
        {
          id: 'g3-en-can-activities-l1-e04',
          type: 'match',
          pairs: [
            ['shells', 'мушлі'],
            ['puzzles', 'пазли'],
            ['teddy bears', 'плюшеві ведмедики'],
          ],
        },
        {
          id: 'g3-en-can-activities-l1-e05',
          type: 'type',
          prompt: 'Напиши англійською: мушлі',
          answer: 'shells',
        },
        {
          id: 'g3-en-can-activities-l1-e06',
          type: 'type',
          prompt: 'Напиши англійською: пазли',
          answer: 'puzzles',
        },
        {
          id: 'g3-en-can-activities-l1-e07',
          type: 'type',
          prompt: 'Напиши англійською: плюшеві ведмедики',
          answer: 'teddy bears',
        },
        {
          id: 'g3-en-can-activities-l1-e08',
          type: 'choice',
          prompt: 'Що означає "teddy bears"?',
          options: ['плюшеві ведмедики', 'пазли', 'мушлі'],
          answer: 'плюшеві ведмедики',
          speak: true,
        },
        {
          id: 'g3-en-can-activities-l1-e09',
          type: 'choice',
          prompt: 'Вибери правильний варіант для "мушлі"',
          options: ['bears', 'shells', 'puzzles'],
          answer: 'shells',
          speak: true,
        },
      ],
    },
    {
      id: 'g3-en-can-activities-l2',
      title: 'Заняття',
      exercises: [
        {
          id: 'g3-en-can-activities-l2-e01',
          type: 'choice',
          prompt: 'Як кажуть "займатися карате"?',
          options: ['play basketball', 'do karate', 'sing'],
          answer: 'do karate',
          speak: true,
        },
        {
          id: 'g3-en-can-activities-l2-e02',
          type: 'choice',
          prompt: 'Яка активність "грати в баскетбол"?',
          options: ['play basketball', 'dance', 'paint'],
          answer: 'play basketball',
          speak: true,
        },
        {
          id: 'g3-en-can-activities-l2-e03',
          type: 'choice',
          prompt: 'Як англійською "співати"?',
          options: ['dance', 'sing', 'dive'],
          answer: 'sing',
          speak: true,
        },
        {
          id: 'g3-en-can-activities-l2-e04',
          type: 'choice',
          prompt: 'Яке слово означає "танцювати"?',
          options: ['paint', 'sing', 'dance'],
          answer: 'dance',
          speak: true,
        },
        {
          id: 'g3-en-can-activities-l2-e05',
          type: 'choice',
          prompt: 'Як кажуть "малювати (фарбами)"?',
          options: ['dive', 'sing', 'paint'],
          answer: 'paint',
          speak: true,
        },
        {
          id: 'g3-en-can-activities-l2-e06',
          type: 'choice',
          prompt: 'Яка активність "пірнати"?',
          options: ['dance', 'paint', 'dive'],
          answer: 'dive',
          speak: true,
        },
        {
          id: 'g3-en-can-activities-l2-e07',
          type: 'match',
          pairs: [
            ['do karate', 'займатися карате'],
            ['play basketball', 'грати в баскетбол'],
            ['sing', 'співати'],
            ['dance', 'танцювати'],
          ],
        },
        {
          id: 'g3-en-can-activities-l2-e08',
          type: 'match',
          pairs: [
            ['paint', 'малювати'],
            ['dive', 'пірнати'],
            ['do karate', 'займатися карате'],
            ['play basketball', 'грати в баскетбол'],
          ],
        },
        {
          id: 'g3-en-can-activities-l2-e09',
          type: 'type',
          prompt: 'Напиши англійською: займатися карате',
          answer: 'do karate',
        },
        {
          id: 'g3-en-can-activities-l2-e10',
          type: 'type',
          prompt: 'Напиши англійською: пірнати',
          answer: 'dive',
        },
        {
          id: 'g3-en-can-activities-l2-e11',
          type: 'match',
          pairs: [
            ['do karate', 'займатися карате'],
            ['play basketball', 'грати в баскетбол'],
            ['paint', 'малювати'],
            ['dive', 'пірнати'],
          ],
        },
        {
          id: 'g3-en-can-activities-l2-e12',
          type: 'match',
          pairs: [
            ['sing', 'співати'],
            ['dance', 'танцювати'],
            ['paint', 'малювати'],
            ['dive', 'пірнати'],
          ],
        },
      ],
    },
    {
      id: 'g3-en-can-activities-l3',
      title: 'Речення з can / can\'t',
      exercises: [
        {
          id: 'g3-en-can-activities-l3-e01',
          type: 'order',
          prompt: 'Склади речення: Вона вміє співати.',
          tokens: ['sing', 'She', 'dance', 'can'],
          answer: ['She', 'can', 'sing'],
        },
        {
          id: 'g3-en-can-activities-l3-e02',
          type: 'order',
          prompt: 'Склади речення: Він не вміє танцювати.',
          tokens: ['dance', 'He', 'sing', 'can\'t'],
          answer: ['He', 'can\'t', 'dance'],
        },
        {
          id: 'g3-en-can-activities-l3-e03',
          type: 'fill',
          prompt: 'She ___ dive (Вона вміє пірнати)',
          answer: 'can',
          accept: ['can'],
        },
        {
          id: 'g3-en-can-activities-l3-e04',
          type: 'fill',
          prompt: 'He ___ play basketball (Він не вміє грати в баскетбол)',
          answer: 'can\'t',
          accept: ['can\'t', 'cannot'],
        },
        {
          id: 'g3-en-can-activities-l3-e05',
          type: 'order',
          prompt: 'Склади речення: Я вмію дуже добре співати.',
          tokens: ['well', 'I', 'dance', 'very', 'can', 'sing'],
          answer: ['I', 'can', 'sing', 'very', 'well'],
        },
        {
          id: 'g3-en-can-activities-l3-e06',
          type: 'choice',
          prompt: 'Ти вмієш займатися карате. Як відповіси на "Can you do karate?"',
          options: ['Yes, I can', 'No, I cannot', 'Maybe yes'],
          answer: 'Yes, I can',
          speak: true,
        },
        {
          id: 'g3-en-can-activities-l3-e07',
          type: 'fill',
          prompt: 'I ___ sing very well (Я вмію співати дуже добре)',
          answer: 'can',
          accept: ['can'],
        },
        {
          id: 'g3-en-can-activities-l3-e08',
          type: 'fill',
          prompt: 'They ___ dive in the pool (Вони не вміють пірнати в басейні)',
          answer: 'can\'t',
          accept: ['can\'t', 'cannot'],
        },
        {
          id: 'g3-en-can-activities-l3-e09',
          type: 'match',
          pairs: [
            ['can', 'могти, вміти'],
            ['can\'t', 'не могти, не вміти'],
            ['Can you ...?', 'Чи вмієш ти ...?'],
            ['Yes, I can', 'Так, вмію'],
          ],
        },
        {
          id: 'g3-en-can-activities-l3-e10',
          type: 'choice',
          prompt: 'Ти не вмієш малювати. На яке запитання відповіси "No, I can\'t"?',
          options: ['Can you paint?', 'Do you sing?', 'Where are you?'],
          answer: 'Can you paint?',
          speak: true,
        },
        {
          id: 'g3-en-can-activities-l3-e11',
          type: 'type',
          prompt: 'Ти вмієш займатися карате. Дай ствердну відповідь англійською на запитання: Can you do karate?',
          answer: 'Yes, I can',
          accept: ['Yes, I can'],
        },
      ],
    },
  ],
};

export default canActivitiesSection;
