import { Section } from '../../schema';

export const datesSection: Section = {
  id: 'g3-english-dates',
  grade: 3,
  subject: 'english',
  section: 'dates',
  title: 'Як записати дату',
  lessons: [
    {
      id: 'g3-en-dates-l1',
      title: 'Дні тижня',
      exercises: [
        {
          id: 'g3-en-dates-l1-e01',
          type: 'order',
          prompt: 'Склади перші три дні тижня по порядку, починаючи з понеділка.',
          tokens: ['Tuesday', 'Monday', 'Wednesday', 'Sunday'],
          answer: ['Monday', 'Tuesday', 'Wednesday'],
        },
        {
          id: 'g3-en-dates-l1-e02',
          type: 'match',
          pairs: [
            ['Monday', 'понеділок'],
            ['Tuesday', 'вівторок'],
            ['Wednesday', 'середа'],
            ['Thursday', 'четвер'],
          ],
        },
        {
          id: 'g3-en-dates-l1-e03',
          type: 'choice',
          prompt: 'Який день іде після понеділка?',
          options: ['Sunday', 'Tuesday', 'Wednesday'],
          answer: 'Tuesday',
          speak: true,
        },
        {
          id: 'g3-en-dates-l1-e04',
          type: 'choice',
          prompt: 'Як англійською "п\'ятниця"?',
          options: ['Thursday', 'Friday', 'Saturday'],
          answer: 'Friday',
          speak: true,
        },
        {
          id: 'g3-en-dates-l1-e05',
          type: 'match',
          pairs: [
            ['Friday', 'п\'ятниця'],
            ['Saturday', 'субота'],
            ['Sunday', 'неділя'],
            ['Tuesday', 'вівторок'],
          ],
        },
        {
          id: 'g3-en-dates-l1-e06',
          type: 'type',
          prompt: 'Напиши англійською: четвер',
          answer: 'Thursday',
        },
        {
          id: 'g3-en-dates-l1-e07',
          type: 'choice',
          prompt: 'Який день іде перед п\'ятницею?',
          options: ['Wednesday', 'Thursday', 'Saturday'],
          answer: 'Thursday',
          speak: true,
        },
        {
          id: 'g3-en-dates-l1-e08',
          type: 'type',
          prompt: 'Напиши англійською: середа',
          answer: 'Wednesday',
        },
        {
          id: 'g3-en-dates-l1-e09',
          type: 'choice',
          prompt: 'Як кажуть "субота"?',
          options: ['Friday', 'Saturday', 'Sunday'],
          answer: 'Saturday',
          speak: true,
        },
        {
          id: 'g3-en-dates-l1-e10',
          type: 'match',
          pairs: [
            ['Monday', 'понеділок'],
            ['Wednesday', 'середа'],
            ['Friday', 'п\'ятниця'],
            ['Sunday', 'неділя'],
          ],
        },
      ],
    },
    {
      id: 'g3-en-dates-l2',
      title: 'Місяці',
      exercises: [
        {
          id: 'g3-en-dates-l2-e01',
          type: 'order',
          prompt: 'Склади перші три місяці року по порядку, починаючи із січня.',
          tokens: ['February', 'January', 'March', 'April'],
          answer: ['January', 'February', 'March'],
        },
        {
          id: 'g3-en-dates-l2-e02',
          type: 'match',
          pairs: [
            ['January', 'січень'],
            ['February', 'лютий'],
            ['March', 'березень'],
            ['April', 'квітень'],
          ],
        },
        {
          id: 'g3-en-dates-l2-e03',
          type: 'choice',
          prompt: 'Як англійською "травень"?',
          options: ['April', 'May', 'June'],
          answer: 'May',
          speak: true,
        },
        {
          id: 'g3-en-dates-l2-e04',
          type: 'match',
          pairs: [
            ['May', 'травень'],
            ['June', 'червень'],
            ['July', 'липень'],
            ['August', 'серпень'],
          ],
        },
        {
          id: 'g3-en-dates-l2-e05',
          type: 'type',
          prompt: 'Напиши англійською: вересень',
          answer: 'September',
        },
        {
          id: 'g3-en-dates-l2-e06',
          type: 'choice',
          prompt: 'Як кажуть "жовтень"?',
          options: ['September', 'October', 'November'],
          answer: 'October',
          speak: true,
        },
        {
          id: 'g3-en-dates-l2-e07',
          type: 'match',
          pairs: [
            ['September', 'вересень'],
            ['October', 'жовтень'],
            ['November', 'листопад'],
            ['December', 'грудень'],
          ],
        },
        {
          id: 'g3-en-dates-l2-e08',
          type: 'type',
          prompt: 'Напиши англійською: листопад',
          answer: 'November',
        },
        {
          id: 'g3-en-dates-l2-e09',
          type: 'choice',
          prompt: 'Який місяць перед груднем?',
          options: ['October', 'November', 'January'],
          answer: 'November',
          speak: true,
        },
        {
          id: 'g3-en-dates-l2-e10',
          type: 'match',
          pairs: [
            ['January', 'січень'],
            ['June', 'червень'],
            ['September', 'вересень'],
            ['December', 'грудень'],
          ],
        },
      ],
    },
    {
      id: 'g3-en-dates-l3',
      title: 'Порядкові числа',
      exercises: [
        {
          id: 'g3-en-dates-l3-e01',
          type: 'match',
          pairs: [
            ['1st', 'the first'],
            ['2nd', 'the second'],
            ['3rd', 'the third'],
            ['4th', 'the fourth'],
          ],
        },
        {
          id: 'g3-en-dates-l3-e02',
          type: 'match',
          pairs: [
            ['5th', 'the fifth'],
            ['6th', 'the sixth'],
            ['7th', 'the seventh'],
            ['8th', 'the eighth'],
          ],
        },
        {
          id: 'g3-en-dates-l3-e03',
          type: 'match',
          pairs: [
            ['9th', 'the ninth'],
            ['10th', 'the tenth'],
            ['11th', 'the eleventh'],
            ['12th', 'the twelfth'],
          ],
        },
        {
          id: 'g3-en-dates-l3-e04',
          type: 'match',
          pairs: [
            ['13th', 'the thirteenth'],
            ['14th', 'the fourteenth'],
            ['15th', 'the fifteenth'],
            ['16th', 'the sixteenth'],
          ],
        },
        {
          id: 'g3-en-dates-l3-e05',
          type: 'match',
          pairs: [
            ['17th', 'the seventeenth'],
            ['18th', 'the eighteenth'],
            ['19th', 'the nineteenth'],
            ['20th', 'the twentieth'],
          ],
        },
        {
          id: 'g3-en-dates-l3-e06',
          type: 'match',
          pairs: [
            ['21st', 'the twenty-first'],
            ['22nd', 'the twenty-second'],
            ['23rd', 'the twenty-third'],
            ['24th', 'the twenty-fourth'],
          ],
        },
        {
          id: 'g3-en-dates-l3-e07',
          type: 'match',
          pairs: [
            ['25th', 'the twenty-fifth'],
            ['26th', 'the twenty-sixth'],
            ['27th', 'the twenty-seventh'],
            ['28th', 'the twenty-eighth'],
          ],
        },
        {
          id: 'g3-en-dates-l3-e08',
          type: 'choice',
          prompt: 'Вибери правильне написання для 20-го',
          options: ['the twentieh', 'the twentieth', 'the twentith'],
          answer: 'the twentieth',
          speak: true,
        },
        {
          id: 'g3-en-dates-l3-e09',
          type: 'match',
          pairs: [
            ['29th', 'the twenty-ninth'],
            ['30th', 'the thirtieth'],
            ['31st', 'the thirty-first'],
          ],
        },
        {
          id: 'g3-en-dates-l3-e10',
          type: 'type',
          prompt: 'Напиши англійською: третій',
          answer: 'the third',
          accept: ['the third', 'third', 'the 3rd', '3rd'],
        },
        {
          id: 'g3-en-dates-l3-e11',
          type: 'type',
          prompt: 'Напиши англійською: дванадцятий',
          answer: 'the twelfth',
          accept: ['the twelfth', 'twelfth', 'the 12th', '12th'],
        },
      ],
    },
    {
      id: 'g3-en-dates-l4',
      title: 'Записуємо дату',
      exercises: [
        {
          id: 'g3-en-dates-l4-e01',
          type: 'order',
          prompt: 'Склади дату англійською: вівторок, 15 вересня.',
          tokens: ['September', '15th', 'Tuesday,', 'of', 'the'],
          answer: ['Tuesday,', 'the', '15th', 'of', 'September'],
        },
        {
          id: 'g3-en-dates-l4-e02',
          type: 'fill',
          prompt: 'Monday, ___ 10th of March (понеділок, 10 березня)',
          answer: 'the',
          accept: ['the'],
        },
        {
          id: 'g3-en-dates-l4-e03',
          type: 'fill',
          prompt: 'Wednesday, the ___ of June (середа, 3 червня). Напиши порядкове число.',
          answer: '3rd',
          accept: ['3rd', 'third'],
        },
        {
          id: 'g3-en-dates-l4-e04',
          type: 'choice',
          prompt: 'Яка правильна дата англійською для четверга, 25 грудня?',
          options: [
            'Thursday the 25 of December',
            'Thursday, the 25th of December',
            'Thursday the 25th December',
          ],
          answer: 'Thursday, the 25th of December',
          speak: true,
        },
        {
          id: 'g3-en-dates-l4-e05',
          type: 'fill',
          prompt: 'Friday, the 1st ___ September (п\'ятниця, 1 вересня)',
          answer: 'of',
          accept: ['of'],
        },
        {
          id: 'g3-en-dates-l4-e06',
          type: 'choice',
          prompt: 'Вибери правильне написання дати: вівторок, 12 січня.',
          options: [
            'Tuesday, the 12 of January',
            'Tuesday the 12th of January',
            'Tuesday, the 12th of January',
          ],
          answer: 'Tuesday, the 12th of January',
          speak: true,
        },
        {
          id: 'g3-en-dates-l4-e07',
          type: 'match',
          pairs: [
            ['Classwork', 'класна робота'],
            ['Homework', 'домашня робота'],
            ['Ex.', 'вправа'],
            ['P.', 'сторінка'],
          ],
        },
        {
          id: 'g3-en-dates-l4-e08',
          type: 'type',
          prompt: 'Напиши англійською дату: середа, 1 жовтня',
          answer: 'Wednesday, the 1st of October',
          accept: ['Wednesday, the 1st of October', 'Wednesday, the first of October'],
        },
        {
          id: 'g3-en-dates-l4-e09',
          type: 'choice',
          prompt: 'Що означає "October"?',
          options: ['жовтень', 'липень', 'вересень'],
          answer: 'жовтень',
          speak: true,
        },
        {
          id: 'g3-en-dates-l4-e10',
          type: 'fill',
          prompt: 'Saturday, the 8th ___ May (субота, 8 травня)',
          answer: 'of',
          accept: ['of'],
        },
        {
          id: 'g3-en-dates-l4-e11',
          type: 'order',
          prompt: 'Склади дату англійською: п\'ятниця, 20 жовтня.',
          tokens: ['20th', 'Friday,', 'the', 'October', 'of'],
          answer: ['Friday,', 'the', '20th', 'of', 'October'],
        },
      ],
    },
  ],
};

export default datesSection;
