import { Section } from '../../schema';

export const numbers10To100Section: Section = {
  id: 'g3-english-numbers-10-100',
  grade: 3,
  subject: 'english',
  section: 'numbers-10-100',
  title: 'Числа 10-100',
  lessons: [
    {
      id: 'g3-en-numbers-10-100-l1',
      title: 'Числа 10-20',
      exercises: [
        {
          id: 'g3-en-numbers-10-100-l1-e01',
          type: 'match',
          pairs: [
            ['10', 'ten'],
            ['11', 'eleven'],
            ['12', 'twelve'],
            ['13', 'thirteen'],
          ],
        },
        {
          id: 'g3-en-numbers-10-100-l1-e02',
          type: 'match',
          pairs: [
            ['14', 'fourteen'],
            ['15', 'fifteen'],
            ['16', 'sixteen'],
            ['17', 'seventeen'],
          ],
        },
        {
          id: 'g3-en-numbers-10-100-l1-e03',
          type: 'match',
          pairs: [
            ['18', 'eighteen'],
            ['19', 'nineteen'],
            ['20', 'twenty'],
            ['15', 'fifteen'],
          ],
        },
        {
          id: 'g3-en-numbers-10-100-l1-e04',
          type: 'type',
          prompt: 'Напиши англійською число: 10',
          answer: 'ten',
        },
        {
          id: 'g3-en-numbers-10-100-l1-e05',
          type: 'type',
          prompt: 'Напиши англійською число: 12',
          answer: 'twelve',
        },
        {
          id: 'g3-en-numbers-10-100-l1-e06',
          type: 'type',
          prompt: 'Напиши англійською число: 15',
          answer: 'fifteen',
        },
        {
          id: 'g3-en-numbers-10-100-l1-e07',
          type: 'choice',
          prompt: 'Як англійською число 11?',
          options: ['ten', 'eleven', 'twelve'],
          answer: 'eleven',
          speak: true,
        },
        {
          id: 'g3-en-numbers-10-100-l1-e08',
          type: 'choice',
          prompt: 'Яке число це "nineteen"?',
          options: ['17', '18', '19'],
          answer: '19',
          speak: true,
        },
        {
          id: 'g3-en-numbers-10-100-l1-e09',
          type: 'type',
          prompt: 'Напиши англійською число: 20',
          answer: 'twenty',
        },
        {
          id: 'g3-en-numbers-10-100-l1-e10',
          type: 'choice',
          prompt: 'Як кажуть число 14?',
          options: ['fourteen', 'forty', 'thirteen'],
          answer: 'fourteen',
          speak: true,
        },
        {
          id: 'g3-en-numbers-10-100-l1-e11',
          type: 'type',
          prompt: 'Напиши англійською число: 17',
          answer: 'seventeen',
        },
        {
          id: 'g3-en-numbers-10-100-l1-e12',
          type: 'match',
          pairs: [
            ['11', 'eleven'],
            ['13', 'thirteen'],
            ['18', 'eighteen'],
            ['20', 'twenty'],
          ],
        },
      ],
    },
    {
      id: 'g3-en-numbers-10-100-l2',
      title: 'Десятки',
      exercises: [
        {
          id: 'g3-en-numbers-10-100-l2-e01',
          type: 'match',
          pairs: [
            ['20', 'twenty'],
            ['30', 'thirty'],
            ['40', 'forty'],
            ['50', 'fifty'],
          ],
        },
        {
          id: 'g3-en-numbers-10-100-l2-e02',
          type: 'match',
          pairs: [
            ['60', 'sixty'],
            ['70', 'seventy'],
            ['80', 'eighty'],
            ['90', 'ninety'],
          ],
        },
        {
          id: 'g3-en-numbers-10-100-l2-e03',
          type: 'type',
          prompt: 'Напиши англійською число: 30',
          answer: 'thirty',
        },
        {
          id: 'g3-en-numbers-10-100-l2-e04',
          type: 'type',
          prompt: 'Напиши англійською число: 40',
          answer: 'forty',
        },
        {
          id: 'g3-en-numbers-10-100-l2-e05',
          type: 'choice',
          prompt: 'Правильне написання для 40 це:',
          options: ['fourty', 'forty', 'fourthy'],
          answer: 'forty',
          speak: true,
        },
        {
          id: 'g3-en-numbers-10-100-l2-e06',
          type: 'choice',
          prompt: 'Вибери помилку в написанні:',
          options: ['fifty', 'fourty', 'seventy'],
          answer: 'fourty',
          speak: true,
        },
        {
          id: 'g3-en-numbers-10-100-l2-e07',
          type: 'type',
          prompt: 'Напиши англійською число: 60',
          answer: 'sixty',
        },
        {
          id: 'g3-en-numbers-10-100-l2-e08',
          type: 'choice',
          prompt: 'Як кажуть число 90?',
          options: ['ninty', 'ninety', 'nienty'],
          answer: 'ninety',
          speak: true,
        },
        {
          id: 'g3-en-numbers-10-100-l2-e09',
          type: 'type',
          prompt: 'Напиши англійською число: 100',
          answer: 'one hundred',
          accept: ['one hundred', 'a hundred'],
        },
        {
          id: 'g3-en-numbers-10-100-l2-e10',
          type: 'match',
          pairs: [
            ['50', 'fifty'],
            ['70', 'seventy'],
            ['80', 'eighty'],
            ['100', 'one hundred'],
          ],
        },
        {
          id: 'g3-en-numbers-10-100-l2-e11',
          type: 'type',
          prompt: 'Напиши англійською число: 80',
          answer: 'eighty',
        },
      ],
    },
    {
      id: 'g3-en-numbers-10-100-l3',
      title: 'Числа 21-99',
      exercises: [
        {
          id: 'g3-en-numbers-10-100-l3-e01',
          type: 'type',
          prompt: 'Напиши англійською число: 21',
          answer: 'twenty-one',
          accept: ['twenty-one', 'twenty one'],
        },
        {
          id: 'g3-en-numbers-10-100-l3-e02',
          type: 'type',
          prompt: 'Напиши англійською число: 35',
          answer: 'thirty-five',
          accept: ['thirty-five', 'thirty five'],
        },
        {
          id: 'g3-en-numbers-10-100-l3-e03',
          type: 'choice',
          prompt: 'Як кажуть число 68?',
          options: ['sixty-eight', 'sixteen-eight', 'eighty-six'],
          answer: 'sixty-eight',
          speak: true,
        },
        {
          id: 'g3-en-numbers-10-100-l3-e04',
          type: 'choice',
          prompt: 'Вибери число для "forty-two"',
          options: ['24', '42', '34'],
          answer: '42',
          speak: true,
        },
        {
          id: 'g3-en-numbers-10-100-l3-e05',
          type: 'order',
          prompt: 'Склади речення: Я вмію рахувати до двадцяти.',
          tokens: ['count', 'I', 'can', 'to', 'twenty'],
          answer: ['I', 'can', 'count', 'to', 'twenty'],
        },
        {
          id: 'g3-en-numbers-10-100-l3-e06',
          type: 'type',
          prompt: 'Напиши англійською число: 47',
          answer: 'forty-seven',
          accept: ['forty-seven', 'forty seven'],
        },
        {
          id: 'g3-en-numbers-10-100-l3-e07',
          type: 'type',
          prompt: 'Напиши англійською число: 89',
          answer: 'eighty-nine',
          accept: ['eighty-nine', 'eighty nine'],
        },
        {
          id: 'g3-en-numbers-10-100-l3-e08',
          type: 'choice',
          prompt: 'Яке число це "ninety-two"?',
          options: ['29', '92', '39'],
          answer: '92',
          speak: true,
        },
        {
          id: 'g3-en-numbers-10-100-l3-e09',
          type: 'choice',
          prompt: 'Яка різниця між "thirteen" та "thirty"?',
          options: [
            '"thirteen" це 13, "thirty" це 30',
            'Немає різниці',
            '"thirteen" більше',
          ],
          answer: '"thirteen" це 13, "thirty" це 30',
          speak: true,
        },
        {
          id: 'g3-en-numbers-10-100-l3-e10',
          type: 'type',
          prompt: 'Напиши англійською число: 54',
          answer: 'fifty-four',
          accept: ['fifty-four', 'fifty four'],
        },
        {
          id: 'g3-en-numbers-10-100-l3-e11',
          type: 'choice',
          prompt: 'Як кажуть число 73?',
          options: ['seventy-three', 'thirty-seven', 'eighty-three'],
          answer: 'seventy-three',
          speak: true,
        },
        {
          id: 'g3-en-numbers-10-100-l3-e12',
          type: 'type',
          prompt: 'Напиши англійською число: 91',
          answer: 'ninety-one',
          accept: ['ninety-one', 'ninety one'],
        },
      ],
    },
  ],
};

export default numbers10To100Section;
